#!/bin/bash

if [ "$1" == "configure" ]; then
    printf "\n* Post-installing...\n"

    printf "\n* Setting up unattended-upgrades...\n"
    sed -i -r -e 's#.*Unattended-Upgrade::SyslogEnable .*#Unattended-Upgrade::SyslogEnable "true";#' -e 's#.*Unattended-Upgrade::SyslogFacility .*#Unattended-Upgrade::SyslogFacility "local5";#' /etc/apt/apt.conf.d/50unattended-upgrades

    printf "\n* Setting up nginx...\n"
    if [ -f /etc/nginx/sites-enabled/default ]; then
        rm -f /etc/nginx/sites-enabled/default
    fi

    # Config nginx to log via syslog-ng only.
    sed -i '/access_log/d' /etc/nginx/nginx.conf
    sed -i '/error_log/d' /etc/nginx/nginx.conf

    # Fix the syslog-ng main file. Needed to avoid logging also in /var/log/syslog.
    cd /etc/syslog-ng/
    # Move the inclusion of the conf.d files before the log path entries if needed.
    if grep -Eq '[iI]nclude.*/etc/syslog-ng/conf.d/' syslog-ng.conf; then
        # Backup the main config file.
        cp syslog-ng.conf "syslog-ng.conf.`date +%Y%m%d.%H%M`"

        # Cleanup the current include directive.
        sed -i -r -e '/[iI]nclude.*\/etc\/syslog-ng\/conf.d\//d' syslog-ng.conf
        sed -i -r '${/^#+/d;}' syslog-ng.conf
        sed -i -r '${/^#+/d;}' syslog-ng.conf

        # Add the include directive in the right place.
        sed -i -e '/# Log paths/i # Include all config files in \/etc\/syslog-ng\/conf.d\/\n########################\n@include "\/etc\/syslog-ng\/conf.d\/*.conf"\n\n\n########################' syslog-ng.conf
    fi

    printf "\n* Enabling local services...\n"
    systemctl enable syslog-ng
    systemctl enable consul
    systemctl enable consul_template
    systemctl enable unattended-upgrades

    printf "\n* Post-install accomplished.\n"
fi

exit 0
