#!/bin/bash

# Use image label to cleanup possible orphaned images.
oImgs=$(buildah images | grep -F '<none>' | awk '{print $3}')
for img in $oImgs ; do
    if buildah inspect $img | grep -q '"AUTOMATION_CONTAINER_IMAGE": "revp"'; then
        buildah rmi --force $img
    fi
done

if [ "$1" == "purge" ]; then
    if podman volume ls | awk '{print $2}' | grep -q ^revp$; then
        printf "\n* Clean up revp volume...\n"
        podman volume rm revp
    fi
fi

# Force debconf cleanup.
echo PURGE | debconf-communicate automation-interface-reverse-proxy-container

exit 0
